server:
  port: 9999

spring:
  application:
    name: mq-service-provider
  rabbitmq:
    host: 192.168.199.234
    username: guest
    password: guest
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


